default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: coference_development
  pool: 5
  host: localhost
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: coference_test
  pool: 5
  username: root
  password:

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
